index:
    path: /
    controller: App\Controller\MainController::index
about_us:
    path: /about_us
    controller: App\Controller\MainController::aboutAs

contact_us:
    path: /contact_us
    controller: App\Controller\MainController::contuctAs

statistic:
    path: /statistic
    controller: App\Controller\MainController::statistic

tos:
    path: /tos
    controller: App\Controller\MainController::tos

api:
    path: /api
    controller: App\Controller\MainController::api

faq:
    path: /faq
    controller: App\Controller\MainController::faq

login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: [GET]

admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::dashboard

admin_files:
    path: /admin/files/{page}
    controller: App\Controller\Admin\FilesController::files
    defaults:   { page: 1 }

admin_edit_file:
    path: /admin/file/{id}
    controller: App\Controller\Admin\FilesController::editFile

admin_store_file:
    path: /admin/file/store/{id}
    controller: App\Controller\Admin\FilesController::store
    methods: [POST]

admin_destruct_file:
    path: /admin/file/destruct/{id}
    controller: App\Controller\Admin\FilesController::destruct
    methods: [GET]

admin_pages:
    path: /admin/pages
    controller: App\Controller\Admin\PageController::pages

admin_edit_page:
    path: /admin/page/{id}/{lang}
    controller: App\Controller\Admin\PageController::editPage
    defaults:   { lang: en }

admin_edit_page_image:
    path: /admin/page/image/
    controller: App\Controller\Admin\PageController::addImage
    methods: [POST]

admin_store_page:
    path: /admin/store/page/{id}/{lang}
    controller: App\Controller\Admin\PageController::store
    defaults:   { lang: en }
    methods: [POST]

admin_reports:
    path: /admin/reports
    controller: App\Controller\AdminController::reports

admin_edit_reports:
    path: /admin/report/{id}
    controller: App\Controller\AdminController::editReports

admin_languages:
    path: /admin/languages
    controller: App\Controller\AdminController::languages

admin_edit_translation:
    path: /admin/translation/{id}
    controller: App\Controller\AdminController::editTranslation

admin_config:
    path: /admin/config
    controller: App\Controller\AdminController::config

admin_apps:
    path: /admin/apps/{page}
    controller: App\Controller\Admin\AppController::apps
    defaults:   { page: 1 }

admin_edit_app:
    path: /admin/app/{id}
    controller: App\Controller\Admin\AppController::editApp
    methods: [GET]

admin_add_app:
    path: /admin/app
    controller: App\Controller\Admin\AppController::addApp
    methods: [GET]

admin_store_app:
    path: /admin/store/app/{id}
    controller: App\Controller\Admin\AppController::store
    methods: [POST]
    defaults:   { id: 0 }

js_sdk:
    path: /js/sag-sdk.js
    controller: App\Controller\JsSdkController::jsSdk
    methods: [get]

get_file_by_hash:
    path: /f/{hash}
    controller: App\Controller\FileController::getFileByHash
    methods: [get]

get_zip_by_hash:
    path: /g/{hash}
    controller: App\Controller\FileController::getAllFilesByHash
    methods: [get]

set_locale:
    path: /lang/{locale}
    controller: App\Controller\MainController::setLocale
    methods: [get]
    defaults:   { locale: en }